name: Continuous Integration
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  read-all

jobs:
  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      # Checkout rep
      - name: Clone rep
        uses: actions/checkout@v3
      # Set up Flutter
      - name: Clone Flutter rep with master channel
        uses: subosito/flutter-action@v2
      # Get packages
      - name: Get Flutter packages
        run: flutter pub get
      # Generate l10n
      - name: Generate l10n
        run: flutter gen-l10n
      # Static analysis
      - name: Static analysis
        run: flutter analyze
      # Check code formatting
      - name: Check code formatting
        run: flutter format --set-exit-if-changed --dry-run .
      # Run unit tests
      - name: Run unit tests
        run: flutter test